baseURL = 'https://xiahou.me/'
languageCode = 'zh-cn'
title = '夏侯'

[params]
subtitle = "1"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.about]]
name = "About"
url = "/about"
weight = 2

[[menu.tags]]
name = "Tags"
url = "/tags"
weight = 3
