baseURL = 'https://xiahou.me/'
languageCode = 'zh-cn'
title = '夏侯'
theme = "ink"

[params]
subtitle = "Crisp, minimal personal [blog theme for Hugo](https://github.com/knadh/hugo-ink)"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.about]]
name = "About"
url = "/about"
weight = 3
