googleAnalytics = "G-DNH8N6LQ76"
baseURL = 'https://xiahou.me/'
languageCode = 'zh-Hans'
title = 'XiaHou.me'
theme = 'hugo-book'
hasCJKLanguage = true



[[markup]]
  [[markup.goldmark]]
    [[markup.goldmark.parser]]
      [[markup.goldmark.parser.attribute]]
        block = true
    [[markup.goldmark.renderer]]
      unsafe = true
  [[markup.tableOfContents]]
    startLevel = 1


[[menu.before]]
  name = "Blog"
  pageRef = '/posts'
  weight = 2


[[menu.after]]
  name = "Github"
  url = "https://github.com/i1os"
  weight = 2


# [params]
#   BookTheme = "dark"
